// Code generated by goctl. DO NOT EDIT.
package types

type Log struct {
	Type      string `json:"type"`
	Message   string `json:"message"`
	Timestamp int64  `json:"timestamp"`
}

type AuthRequest struct {
	Address   string `json:"address"`
	Signature string `json:"signature"`
}

type AuthResponse struct {
	Auth        bool    `json:"auth"`
	AccessToken *string `json:"accessToken,omitempty"`
}

type GraphTemplate struct {
	IdGraphsTemplates int64  `json:"idgraphsTemplates"`
	Title             string `json:"title"`
	Key               string `json:"key"`
	Bytes             string `json:"bytes"`
	Description       string `json:"description"`
	CustomImg         string `json:"customImg"`
}

type GetGraphsTemplateRequest struct {
	Id int64 `path:"id"`
}

type GetGraphsTemplateResponse struct {
	Success  bool           `json:"success"`
	Template *GraphTemplate `json:"template,omitempty"`
}

type LogsRequest struct {
	Hash string `json:"hash"`
}

type LogsResponse struct {
	Logs []Log `json:"logs"`
}

type DeployRequest struct {
	Alias string `json:"alias"`
	Bytes string `json:"bytes"`
	Debug bool   `json:"debug"`
	State int    `json:"state"`
}

type DeployResponse struct {
	Hash string `json:"hash"`
}

type CompressRequest struct {
	Data string `json:"data"`
}

type CompressResponse struct {
	Compressed string `json:"compressed"`
	Hash       string `json:"hash"`
}

type DecompressRequest struct {
	Data string `json:"data"`
}

type DecompressResponse struct {
	Decompressed string `json:"decompressed"`
	Hash         string `json:"hash"`
}
